//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSistema_TecnicoEntities : DbContext
    {
        public dbSistema_TecnicoEntities()
            : base("name=dbSistema_TecnicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrador> Administrador { get; set; }
        public DbSet<Especialidad> Especialidad { get; set; }
        public DbSet<Pabellon> Pabellon { get; set; }
        public DbSet<Sede> Sede { get; set; }
        public DbSet<Solicitante> Solicitante { get; set; }
        public DbSet<Tecnico> Tecnico { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
        public DbSet<TipoSolicitud> TipoSolicitud { get; set; }
    }
}
