//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnico
    {
        public Tecnico()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int IdTecnico { get; set; }
        public string CTecnico { get; set; }
        public string DNombres { get; set; }
        public string DApellidos { get; set; }
        public string DContrasena { get; set; }
        public int IdEspecialidad { get; set; }
        public int IdSede { get; set; }
        public System.DateTime FCreacion { get; set; }
        public bool DActivo { get; set; }
        public string DCorreo { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
