//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int IdTicket { get; set; }
        public string DTitulo { get; set; }
        public int IdTipoSolicitud { get; set; }
        public string DDescripcion { get; set; }
        public int IdSede { get; set; }
        public int IdPabellon { get; set; }
        public string DEstado { get; set; }
        public string DPrioridad { get; set; }
        public string DComentario { get; set; }
        public System.DateTime FCreacion { get; set; }
        public Nullable<System.DateTime> FActualizacion { get; set; }
        public int IdCreadoPor { get; set; }
        public Nullable<int> IdAtendidoPor { get; set; }
        public Nullable<int> IdAsignadoPor { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Pabellon Pabellon { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual Solicitante Solicitante { get; set; }
        public virtual Tecnico Tecnico { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
    }
}
