//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSolicitud
    {
        public TipoSolicitud()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int IdTipoSolicitud { get; set; }
        public string DNombre { get; set; }
        public bool DActivo { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
